Add gym and pygame to tensorflow image
stfc/cloud-docker-images pull request #22
Opened 2023-07-27 13:04 UTC by DavidFair

Adds PyGame and Gym to the Tensorflow image for an upcoming SciML course.

As these are relatively small deps, I'll add them to the tensorflow image by default rather than create a new one

2023-07-27 15:19 UTC, anish-mudaraddi requested changes

2023-07-27 15:19 UTC, anish-mudaraddi commented on jupyter-tensorflow-notebook/Dockerfile
> -    && rm -rf /var/lib/apt/lists/*
I can't see any of the upstream docker containers install the `nvidia` or `opengl` packages - are they not needed anymore?

2023-07-31 15:56 UTC, anish-mudaraddi commented on jupyter-tensorflow-notebook/Dockerfile
> -    && rm -rf /var/lib/apt/lists/*
@meoflynn informs me that these are not needed

2023-07-31 15:56 UTC, anish-mudaraddi approved these changes

2023-08-07 10:11 UTC, meoflynn requested changes
Tensorflow doesn't seem to be picking up GPU devices, there may be some missing dependencies that Tensorflow specifically requires

2023-08-07 10:30 UTC, meoflynn approved these changes
Issues with tensorflow dependencies to be fixed in a future PR

2023-08-07 10:31 UTC, merged