MAINT: Remove watchtower
stfc/cloud-docker-images pull request #47
Opened 2024-10-02 07:24 UTC by khalford

Removing watchower as the images are not being released with the latest tag anymore. Hence, watchtower is not doing anything

2024-10-02 08:48 UTC, RWhiting78 submitted a review, later dismissed

2024-10-02 13:37 UTC, DavidFair requested changes

2024-10-02 13:37 UTC, DavidFair commented on cloud-chatops/docker-compose.yaml
> +    image: harbor.stfc.ac.uk/stfc-cloud/cloud-chatops:<version>
Could we put the version from this repo?

2024-10-03 08:37 UTC, RWhiting78 approved these changes

2024-10-03 10:09 UTC, DavidFair approved these changes

2024-10-03 10:09 UTC, merged