Refactor pr reminder v2
stfc/cloud-docker-images pull request #82
Opened 2024-11-28 10:44 UTC by khalford

### Description:

Rewrite of PR reminder feature:
Merged pr_reminder.py, post_to_dms.py and base_feature.py into one module. The base feature class is not needed anymore as future features will not be inheriting any methods from it, therefore it makes sense to remove it.

---

### Submitter:

Have you done the following?:

* [ ] Labeled the pull request from the following? `major | minor | patch` or `documentation | workflow`
* [ ] Updated the documentation and template config files?
* [ ] Added unit tests for new / untested code?
* [ ] Verified the relevant staging Docker image runs on `dev-cloud-chatops.nubes.rl.ac.uk`?

New / Existing features:
* [ ] Written integration tests?
* [ ] Configured the Slack Application with new commands or permission scope changes?
* [ ] Updated the `version.txt` and `docker-compose.yml` files?

---

### Reviewer:

Have you checked the following?:
* [ ] Version change is appropriate to the code changes? Semantic versioning documentation [here](https://semver.org/)
* [ ] Unit test code coverage is acceptable?
* [ ] Do the CI jobs pass?

2024-11-28 13:39 UTC, meoflynn requested changes

2024-11-28 13:39 UTC, meoflynn commented on cloud-chatops/tests/test_find_prs.py
> +# pylint: disable=R0801
Should this line be removed as the pylintc file does not have this code in it anymore?

2024-11-28 13:41 UTC, meoflynn approved these changes

2024-11-29 09:47 UTC, anish-mudaraddi reviewed
had a chat with @khalford for how to refactor this code for extensibility

2024-11-29 09:49 UTC, anish-mudaraddi approved these changes

2024-11-29 09:49 UTC, merged